online-shop-django-master/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('login/manager/', views.manager_login, name='manager_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='email_template.html'
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html',
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),
]

online-shop-django-master/cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),

]

online-shop-django-master/online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online-shop-django-master/orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path('create', views.create_order, name='create_order'),
    path('list', views.user_orders, name='user_orders'),
    path('checkout/<int:order_id>', views.checkout, name='checkout'),
    path('fake-payment/<int:order_id>', views.fake_payment, name='pay_order')
]

online-shop-django-master/shop/urls.py
from django.urls import path
from shop import views


app_name = "shop"

urlpatterns = [
	path('', views.home_page, name='home_page'),
	path('<slug:slug>', views.product_detail, name='product_detail'),
	path('add/favorites/<int:product_id>/', views.add_to_favorites, name='add_to_favorites'),
	path('remove/favorites/<int:product_id>/', views.remove_from_favorites, name='remove_from_favorites'),
	path('favorites/', views.favorites, name='favorites'),
	path('search/', views.search, name='search'),
	path('filter/<slug:slug>/', views.filter_by_category, name='filter_by_category'),
	path('company/', views.company, name='company'),
	path('vozvrat/', views.vozvrat, name='vozvrat'),
	path('dogovor/', views.dogovor, name='dogovor'),
	path('dostavka/', views.dostavka, name='dostavka'),
]

online-shop-django-master/shop/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify


class Category(models.Model):
    title = models.CharField(max_length=200)
    sub_category = models.ForeignKey(
        'self', on_delete=models.CASCADE,
        related_name='sub_categories', null=True, blank=True
    )
    is_sub = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs): # new
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
        

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    image = models.ImageField(upload_to='products')
    title = models.CharField(max_length=250)
    description = models.TextField()
    price = models.IntegerField()
    date_created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return self.slug
        
    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

online-shop-django-master/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from shop.models import Product, Category
from cart.forms import QuantityForm

def company(request):
    return render(request, 'company.html')


def vozvrat(request):
	return render(request, 'vozvrat.html')


def dostavka(request):
	return render(request, 'dostavka.html')

def dogovor(request):
	return render(request, 'dogovor.html')

def paginat(request, list_objects):
	p = Paginator(list_objects, 20)
	page_number = request.GET.get('page')
	try:
		page_obj = p.get_page(page_number)
	except PageNotAnInteger:
		page_obj = p.page(1)
	except EmptyPage:
		page_obj = p.page(p.num_pages)
	return page_obj


def home_page(request):
	products = Product.objects.all()
	context = {'products': paginat(request ,products)}
	return render(request, 'home_page.html', context)


def product_detail(request, slug):
	form = QuantityForm()
	product = get_object_or_404(Product, slug=slug)
	related_products = Product.objects.filter(category=product.category).all()[:5]
	context = {
		'title':product.title,
		'product':product,
		'form':form,
		'favorites':'favorites',
		'related_products':related_products
	}
	if request.user.likes.filter(id=product.id).first():
		context['favorites'] = 'remove'
	return render(request, 'product_detail.html', context)


@login_required
def add_to_favorites(request, product_id):
	product = get_object_or_404(Product, id=product_id)
	request.user.likes.add(product)
	return redirect('shop:product_detail', slug=product.slug)


@login_required
def remove_from_favorites(request, product_id):
	product = get_object_or_404(Product, id=product_id)
	request.user.likes.remove(product)
	return redirect('shop:favorites')


@login_required
def favorites(request):
	products = request.user.likes.all()
	context = {'title':'Favorites', 'products':products}
	return render(request, 'favorites.html', context)


def search(request):
	query = request.GET.get('q')
	products = Product.objects.filter(title__icontains=query).all()
	context = {'products': paginat(request ,products)}
	return render(request, 'home_page.html', context)


def filter_by_category(request, slug):
	"""when user clicks on parent category
	we want to show all products in its sub-categories too
	"""
	result = []
	category = Category.objects.filter(slug=slug).first()
	[result.append(product) \
		for product in Product.objects.filter(category=category.id).all()]
	# check if category is parent then get all sub-categories
	if not category.is_sub:
		sub_categories = category.sub_categories.all()
		# get all sub-categories products
		for category in sub_categories:
			[result.append(product) \
				for product in Product.objects.filter(category=category).all()]
	context = {'products': paginat(request ,result)}
	return render(request, 'home_page.html', context)

online-shop-django-master/shop/templates/base.html
{% load static %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <!-- bootstrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% if title %} {{ title }} {% else %} Django Интернет-магазин {% endif %}</title>
</head>
<body>
  <header class="p-2 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <!-- иконка корзины -->
        {% if request.user.is_authenticated %}
        <b class="text-primary">{{ cart_count }}</b>
        {% endif %}
        <a href="{% url 'cart:show_cart' %}" class="text-primary mt-2 me-2"><i class="material-icons h3">&#xe8cc;</i></a>
        <!-- иконка избранного -->
        {% if request.user.is_authenticated %}
        <b class="text-primary">{{ request.user.get_likes_count}}</b>
        {% endif %}
        <a href="{% url 'shop:favorites' %}" class="text-primary mt-2 me-2"><i class="material-icons h3">&#xe87d;</i></a>
        <!-- Меню -->
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'shop:home_page' %}" class="nav-link px-2 text-dark">Главная</a></li>
          <li><a href="{% url 'shop:dogovor' %}" class="nav-link px-2 text-dark">Заключение договора</a></li>
          <!-- выпадающий список категорий -->
          <div class="dropdown text-end">
            <a href="#" class=" mt-2 me-1 ms-1 text-dark d-block link-dark text-decoration-none dropdown-toggle"id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">Категории</a>
            <ul class="dropdown-menu" aria-labelledby="dropdownUser1">
              {% for category in categories %}
              <!-- проверяем, является ли категория родительской -->
                {% if not category.is_sub %}
                  <!-- родительская -->
                {% if category.slug %}
                    <li><a href="{% url 'shop:filter_by_category' category.slug %}" class="dropdown-item text-capitalize bg-light border"><b>{{ category }}</b></a></li>
                {% endif %}
                  {% for child in category.sub_categories.all %}
                   <!-- дочерняя -->
                   <li><a href="{% url 'shop:filter_by_category' child.slug %}" class="dropdown-item">{{ child }}</a></li>
                  {% endfor %}
                {% endif %}
              {% endfor %}
            </ul>
          </div>
          <li><a href="{% url 'shop:vozvrat' %}" class="nav-link px-2 text-dark">Возврат</a></li>
          <li><a href="{% url 'shop:company' %}" class="nav-link px-2 text-dark">О компании</a></li>
          <li><a href="{% url 'shop:dostavka' %}" class="nav-link px-2 text-dark">Доставка</a></li>
        </ul>
        <!-- форма поиска -->
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{% url 'shop:search' %}">
          <input name="q" type="search" class="form-control form-control-dark" placeholder="Поиск..." aria-label="Поиск">
        </form>
        {% if request.user.is_authenticated %}
        <!-- выпадающий список профиля пользователя -->
        <div class="dropdown text-end">
          <a href="#" class="btn btn-primary text-white me-4 d-block link-dark text-decoration-none dropdown-toggle"id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">Профиль</a>
          <ul class="dropdown-menu" aria-labelledby="dropdownUser1">
            <li><a href="{% url 'cart:show_cart' %}" <a class="dropdown-item">Корзина</a></li>
            <li><a href="{% url 'shop:favorites' %}" <a class="dropdown-item">Избранное</a></li>
            <li><a href="{% url 'orders:user_orders' %}" <a class="dropdown-item">Заказы</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Редактировать профиль</a></li>
            <li><a class="dropdown-item text-danger" href="{% url 'accounts:user_logout' %}">Выйти</a></li>
          </ul>
        </div>
        {% else %}
        <!-- кнопки входа и регистрации -->
        <div class="text-end">
          <a href="{% url 'accounts:user_login' %}" class="btn btn-outline-primary me-2">Войти</a>
          <a href="{% url 'accounts:user_register' %}" class="btn btn-primary">Регистрация</a>
        </div>
        {% endif %}
      </div>
    </div>
  </header>
    <main class="container">
        <div class="row mt-3">
          <!-- сообщения -->
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
          {% endif %}
          <!-- контент -->
          {% block content %}{% endblock %}
        </div>
      </main>
    <!-- Bootstrap JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

online-shop-django-master/shop/templates/company.html
{% extends 'base.html' %}
{% block content %}

 <section id="company">
    <div class="container">
        <div class="company">
            <h1>О компании  РЦ "Luxbrend" - 30 лет опыта продажи  товаров народного потребления</h1>
          <p>Магазин “LUX BREND” является одним из крупнейших оптовых поставщиков одежды, обуви и аксессуаров в Киргизии. Магазин работает с более чем 100 поставщиками Магазин “LUX BREND” является одним из крупнейших оптовых поставщиков одежды в Киргизии. Магазин “ LUX BREND ” работает с более чем 200 поставщиками из разных стран, таких как Узбекистан,Пакистан,Казакстан, Россия и т.д., и обслуживает более чем 1000 клиентов, в том числе розничные магазины, интернет-магазины и т.д. Магазин “ LUX BREND ” предлагает своим клиентам широкий ассортимент женской,мужской и детской одежды, включающий более чем 5000 наименований, таких как платья, юбки, блузки, костюмы, пальто, куртки, свитера, джинсы, брюки, футболки, топы, нижнее белье и т.д. Магазин “ LUX BREND ” постоянно обновляет свой ассортимент в соответствии с модными тенденциями и сезонностью спроса.</p>

        </div>
    </div>
 </section>

{% endblock content %}

online-shop-django-master/shop/templates/dogovor.html
{% extends 'base.html' %}
{% block content %}


<section class="dogovor">
   <div class="container">
  <div class="dogovor">
    <h1>
        Перечень документов для заключения договора</h1>
 <h5>Минимальная сумма заказа: 30 000 сомов</h5>
 <h3>Для индивидуальных предпринимателей:</h3>
 <p> - Свидетельство о регистрации ИП (ИНН); <br>
     - Свидетельство о постановке на налоговый учет (ОГРН); <br>
     - Копия паспорта (страницы с фото и пропиской).
     - Для юридических лиц:</p>

 <h3>Для юридических лиц:</h3>
 <p>
     - Свидетельство о регистрации юридического лица (ИНН); <br>
     - Свидетельство о постановке на налоговый учет (ОГРН); <br>
     - Устав. Страницы, содержащие сведения: об учредителях, о назначении и сроках полномочий директора. А также первая и последняя.
     - Положение о назначении директора.</p>

 <h3>Для физических лиц:</h3>

 <p> - Условия отгрузки физических лиц можно уточнить у менеджера.</p>
  </div>
   </div>
</section>


{% endblock %}

online-shop-django-master/shop/templates/dostavka.html
{% extends 'base.html' %}
{% block content %}


  <section id="dostavka">
    <div class="container">
      <div class="dostavka">
        <div class="dostavka-text">
          <div class="dostavka-info">
            <h3>Прием заявок от клиентов</h3> <br> <span>по мере поступления</span>

          </div>
          <div class="dostavka-info">
            <h3>День доставки</h3> <br> <span>ежедневно</span>

          </div>
    <div class="dostavka-info">
    <h3>Минимальная сумма заказа для бесплатной доставки</h3> <br> <span>от 10 000 сомов</span>

    </div>

        </div>
        <hr>

        <h2>Достака товара следующими транспортными компаниями: <span>транспортными компаниями</span></h2>
        <h1>Инструкция при получение грузов в транспортной компании</h1>
        <p>Во избежание конфликтных ситуаций при получение груза, отправленных через транспортные компании, клиенту (грузополучателю) необходимо: <br>

          1. После оповещения транспортной компанией о прибытии груза получателю следует: <br>

              <span> • предварительно (до получения) ознакомиться с условиями выдачи грузов на сайте ТК и подготовьте нужные документы для получения груза (доверенность на компанию или паспорт); <br></span>

              <span> • при получении необходимо внимательно осмотреть упаковку груза на наличие механических повреждений и нарушений целостности упаковки; <br></span>

              <span> • вскрыть каждую упаковку, если груз запаллетирован и проверить товар по количеству согласно накладной ТК и на наличие повреждений товара внутри паллета. <br></span>

         <span> ВНИМАНИЕ:</span> Все эти действия нужно проводить на территории транспортной компании в присутствии представителя ТК! <br>

          2. В случае, если клиент получил груз у транспортной компании и расписался в сопроводительных документах ответственность несет сам клиент. <br>

          3. Если клиент (грузополучатель) сомневается в сумме доставки груза, то может потребовать перемерить груз на месте.</p>
      </div>
    </div>
          </section>

{% endblock %}

online-shop-django-master/shop/templates/favorites.html
{% extends 'base.html' %}
{% block content %}
{% if products %}
<h2>Ваши Избранные товары</h2>
<hr>
{% for product in products %}
<div class="card me-2 mb-2" style="width: 16rem;">
  <img style="object-fit: cover;" class="card-img mt-2" width="268" height="200" src="{{ product.image.url }}">
  <div class="mt-3 text-center">
    <h5 class="card-title">{{ product.title }}</h5>
    <p class="text-muted">{{ product.price }} руб.</p>
    <a href="{{ product.get_absolute_url }}" class="mb-3 btn btn-primary w-100">Купить сейчас</a>
  </div>
  <a href="{% url 'shop:remove_from_favorites' product.id %}" class="mb-3 btn btn-outline-danger">Убрать из избранного</a>
</div>
{% endfor %}
{% else %}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8 mt-5 pt-5 text-center">
    <br>
    <h3 class="text-muted text-capitalize">Список избранного пуст..!</h3>
    <a href="/" class="text-primary text-decoration-none">Назад</a>
  </div>
  <div class="col-md-2"></div>
</div>
{% endif %}
{% endblock %}

online-shop-django-master/shop/templates/home_page.html
{% extends 'base.html' %}

{% block content %}
{% if products %}
{% for product in products.object_list %}
<div class="card me-2 mb-2" style="width: 16rem;">
    <img style="object-fit: cover;" class="card-img mt-2" width="268" height="200" src="{{ product.image.url }}">
    <div class="mt-3 text-center">
      <h5 class="card-title">{{ product.title }}</h5>
      <p class="text-muted">{{ product.price }} руб.</p>
      <a href="{{ product.get_absolute_url }}" class="mb-3 btn btn-outline-primary w-100">Купить сейчас</a>
    </div>
  </div>
{% endfor %}
<!-- пагинация -->
<center class="mt-5">
  <div class="col-md-2">
    <ul class="pagination">
      {% if products.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Предыдущая</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">{{products.previous_page_number}}</a></li>
      {% endif %}
      <li class="page-item"><a class="page-link" href="?page={{ products.number }}">{{products.number}}</a></li>
      {% if products.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">{{products.next_page_number}}</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Следующая</a></li>
      {% endif %}
    </ul>
  </div>
</center>
{% else %}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8 mt-5 pt-5 text-center">
    <br>
    <h3 class="text-muted text-capitalize">Нет товаров..!</h3>
  </div>
  <div class="col-md-2"></div>
</div>
{% endif %}
{% endblock %}

online-shop-django-master/shop/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="row mb-3 mt-4">
    <div class="col-md-1"></div>
    <!-- содержание продукта -->
    <div class="col-md-5 p-3 border rounded">
        <!-- категория -->
        <div class="border-bottom mb-2 pb-2">
            <span class="text-muted ">Категории:</span><a class="text-decoration-none text-dark" href="{% url 'shop:filter_by_category' product.category.slug %}"> {{product.category}}</a>
        </div>
        <!-- название -->
        <h2>{{ product.title }}</h2>
        <!-- цена -->
        <h4 class="mt-4 text-dark">Цена: ${{ product.price }}</h4>
        <!-- описание -->
        <div class="mt-4 pe-3 mb-5">{{ product.description }}</div>
        <!-- кнопка добавления в корзину -->
        <form method="post" action="{% url 'cart:add_to_cart' product.id %}">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="btn btn-primary mt-4" value="Добавить в корзину">
        </form>
        <br>
        {% if favorites == 'remove' %}
        <a href="{% url 'shop:remove_from_favorites' product.id %}" class="btn btn-outline-danger mt-5 text-capitalize ">{{favorites}} из избранного</a>
        {% else %}
        <a href="{% url 'shop:add_to_favorites' product.id %}" class="btn btn-outline-success mt-5 text-capitalize ">добавить в {{favorites}}</a>
        {% endif %}
    </div>
    <!-- изображение продукта -->
    <div class="col-md-6">
        <img style="object-fit: cover;" class="rounded" src="{{ product.image.url }}" width="510" height="500">
    </div>
</div>
<!-- похожие товары -->
<div class="row mt-4 mb-4">
    <h3>Похожие товары:</h3><hr>
    {% for p in related_products %}

        {% if p != product %}
            <div class="card me-2 mb-2" style="width: 16rem;">
                <img style="object-fit: cover;" class="card-img mt-2" width="268" height="200" src="{{ p.image.url }}">
                <div class="mt-3 text-center">
                <h5 class="card-title">{{ p.title }}</h5>
                <p class="text-muted">${{ p.price }}</p>
                <a href="{{ p.get_absolute_url }}" class="mb-3 btn btn-outline-primary w-100">Купить сейчас</a>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

online-shop-django-master/shop/templates/vozvrat.html
{% extends 'base.html' %}
{% block content %}


<section id="vozvrat">
    <div class="container">
        <div class="vozvrat">
            <p><span>Принимаются в следующих случаях:</span> <br>
                Обнаружение при приёмке скрытого или явного брака; <br>
                Товар пришел в неполной комплектации; <br>
                Пришли позиции отсутствующие в накладной; <br>
                Получены излишки товара; <br>
                Выявлены недостачи при поставке. <br>
                При получении товара через транспортную компанию просим внимательно осматривать коробки на предмет разрывов, <br> повреждения фирменного скотча, наличия вмятин. Внимательно пересчитать коробки и в случае <br> возникновения расхождений составить акт несоответствия с транспортной компанией. <br>

               <span>Сроки подачи претензии:</span> <br>
                5 дней - по недовозу/излишкам при приемке товара; <br>
                14 дней - по явному браку; <br>
                1 месяц - в случае обнаружения скрытых недостатков товара; <br>
                Оформить возврат/претензию по качеству, можно заполнив бланк возврата и отправив его на адрес:Lux Brend <br>

               <span> Мы рассмотрим вашу претензию и сообщим результат в течение 10 календарных дней.</span> <br>


               <span> Шабданова Мээризат</span><br>
                 <span>                Специалист по претензионной работе
</span>
               </p>
        </div>
    </div>
</section>

{% endblock %}